# Generated by Django 5.2.9 on 2025-12-06 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_service_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_image', models.CharField(blank=True, max_length=255, null=True)),
                ('rating', models.IntegerField()),
                ('username', models.CharField(max_length=50)),
                ('user_position', models.CharField(max_length=50)),
                ('review', models.TextField()),
            ],
        ),
    ]
